---
blueprint:
  name: "Play! ZenTasks"
  description: "This is a slight reworking of the Play framework 2.1.x Scala-language sample application - zentasks - to run on Cloud Foundry. The application uses PostgreSQL instead of the in-built H2 in-memory database."
  imageURL: https://raw.github.com/cloudfoundry-blueprints/zentasks-scala-cloudfoundry/master/zentasks_logo.png
  browseURL: https://github.com/cloudfoundry-blueprints/zentasks-scala-cloudfoundry
  buildInstructions: "play dist"
applications:
- name: playzentasks
  framework: play
  runtime: java7
  memory: 512M
  instances: 1
  url: playzentasks.${target-base}
  path: dist/zentask-1.0.zip
  services:
    zentasks-db:
      vendor: postgresql
      version: '9.0'
      tier: free
